#!/bin/bash
set -e

hook_path="./.git/hooks/post-merge"

case "$1" in
  "up")
    ln -sf ../../deploy "${hook_path}"
    ;;
  "down")
    rm -rf "${hook_path}"
    ;;
  *)
    echo "Valid arguments are: up, down."
    exit 1
    ;;
esac
