#!/bin/bash
set -e

hook_path="./.git/hooks/post-merge"

case "$1" in
  )
    $0 up
    ;;
  up|on)
    ln -sf ../../deploy "${hook_path}"
    ;;
  down|off)
    rm -rf "${hook_path}"
    ;;
  *)
    echo "Valid arguments are: <NULL>/up/on, down/off."
    exit 1
    ;;
esac
