#! /bin/bash
set -e

DEPS_DIR="${PWD}/deploy.d/deps.d"

type -p ssh-keygen >/dev/null ||
  "${DEPS_DIR}/install-ssh"

type -p gh >/dev/null ||
  "${DEPS_DIR}/install-gh"

[ -f "${HOME}/.profiledir" ] ||
  "${DEPS_DIR}/install-profiledir"

"${DEPS_DIR}/install-mkays"
