#! /bin/bash
set -e

set -o allexport
. ./app/config/app.conf
set +o allexport

[ -d "${PROFILE_DIR}" ] ||
  mkdir -p "${PROFILE_DIR}"
ln -sf "${PWD}/app/profile" "${PROFILE_DIR}/${APP_NAME}.sh"

[ -d "${BIN_DIR}" ] ||
  mkdir -p "${BIN_DIR}"
ln -sf "${PWD}/app/${APP_PREFIX}"-* "${BIN_DIR}/"

[ -d "${CONFIG_DIR}/${APP_NAME}" ] ||
  mkdir -p "${CONFIG_DIR}/${APP_NAME}"
ln -sf "${PWD}/app/config"/*.conf "${CONFIG_DIR}/${APP_NAME}/"
