#! /bin/bash
set -e

CONF_DIR="./app/config"

[ ! -f "${CONF_DIR}/user.conf" ] &&
    cp "${CONF_DIR}/user.conf.default" "${CONF_DIR}/user.conf"

[ ! -f "${CONF_DIR}/app.conf" ] &&
    cp "${CONF_DIR}/app.conf.default" "${CONF_DIR}/app.conf"

exit 0
