#! /bin/bash

OPTSTRING=":u:r:"
while getopts ${OPTSTRING} opt; do
  case ${opt} in
    u)
      KMN_PUBKEY_USER="${OPTARG}"
      ;;
    r)
      KMN_PUBKEY_REPO="${OPTARG}"
      ;;
    ?)
      echo "Invalid option: -${OPTARG}."
      exit 1
      ;;
  esac
done

repo_local_path="${KMN_PUBKEY_BASEDIR}/${KMN_PUBKEY_REPO}"
# repo_remote_path="git@github.com:${KMN_PUBKEY_USER}/${KMN_PUBKEY_REPO}.git"
repo_ssl_path="https://github.com/${KMN_PUBKEY_USER}/${KMN_PUBKEY_REPO}.git"
repo_ssh_path="git@github.com:${KMN_PUBKEY_USER}/${KMN_PUBKEY_REPO}.git"

# TODO: check if proper git directory exists
[ -d "${repo_local_path}" ] &&
  (cd "${repo_local_path}" && git pull) ||
  git clone "${repo_ssl_path}" "${repo_local_path}"

(cd "${repo_local_path}" &&
  git remote set-url --push origin "${repo_ssh_path}")
