#! /bin/bash

. "${KMN_DIR}/.env"

OPTSTRING=":r:k:"
while getopts ${OPTSTRING} opt; do
  case ${opt} in
    r)
      PUBKEY_REPO="${OPTARG}"
      ;;
    k)
      KEY_NAME="${OPTARG}"
      ;;
    ?)
      echo "Invalid option: -${OPTARG}."
      exit 1
      ;;
  esac
done

repo_local_path="${PUBKEY_BASEDIR}/${PUBKEY_REPO}"
key_pub_path="${HOME}/.ssh/${KEY_NAME}.pub"

cp "${key_pub_path}" "${repo_local_path}"

(cd "${repo_local_path}" &&
    git add --all . &&
    git commit -m "${KEY_NAME}";
    git push)
