#! /bin/bash

OPTSTRING=":r:k:"
while getopts ${OPTSTRING} opt; do
  case ${opt} in
    r)
      KMN_PUBKEY_REPO="${OPTARG}"
      ;;
    k)
      KMN_KEY_NAME="${OPTARG}"
      ;;
    ?)
      echo "Invalid option: -${OPTARG}."
      exit 1
      ;;
  esac
done

repo_local_path="${KMN_PUBKEY_BASEDIR}/${KMN_PUBKEY_REPO}"
key_pub_path="${HOME}/.ssh/${KMN_KEY_NAME}.pub"

cp "${key_pub_path}" "${repo_local_path}"

(cd "${repo_local_path}" &&
    git add --all . &&
    git commit -m "${KMN_KEY_NAME}";
    git push)
