#! /bin/bash

# sudo apt -y update &&
#     sudo apt -y install ssh

OPTSTRING=":t:k:"
while getopts ${OPTSTRING} opt; do
  case ${opt} in
    t)
      KMN_KEY_TYPE="${OPTARG}"
      ;;
    k)
      KMN_KEY_NAME="${OPTARG}"
      ;;
    ?)
      echo "Invalid option: -${OPTARG}."
      exit 1
      ;;
  esac
done

key_priv_path="${HOME}/.ssh/${KMN_KEY_NAME}"
key_id_path="${HOME}/.ssh/id_${KMN_KEY_TYPE}"

# automatically creates dir, if non-existing
ssh-keygen -q -t "${KMN_KEY_TYPE}" -C "${KMN_KEY_NAME}" -f "${key_priv_path}"

# TODO: add argument to make a key default
ln -sf "${key_priv_path}" "${key_id_path}"
ln -sf "${key_priv_path}.pub" "${key_id_path}.pub"
