#! /bin/bash

. "${KMN_CONFIG}

OPTSTRING=":u:e:"
while getopts ${OPTSTRING} opt; do
  case ${opt} in
    u)
      GIT_USERNAME="${OPTARG}"
      ;;
    e)
      GIT_EMAIL="${OPTARG}"
      ;;
    ?)
      echo "Invalid option: -${OPTARG}."
      exit 1
      ;;
  esac
done

echo $GIT_EMAIL
echo $GIT_USERNAME

git config --global user.email "${GIT_EMAIL}" &&
  git config --global user.name "${GIT_USERNAME}"
