#! /bin/bash

. "${KMN_DIR}/.env"

OPTSTRING=":u:r:k:"
while getopts ${OPTSTRING} opt; do
  case ${opt} in
    u)
      PUBKEY_USER="${OPTARG}"
      ;;
    r)
      PUBKEY_REPO="${OPTARG}"
      ;;
    k)
      KEY_NAME="${OPTARG}"
      ;;
    ?)
      echo "Invalid option: -${OPTARG}."
      exit 1
      ;;
  esac
done

gh_baseurl="https://raw.githubusercontent.com/${PUBKEY_USER}/${PUBKEY_REPO}/master"
gh_key_url="${gh_baseurl}/${KEY_NAME}.pub"

curl "${gh_key_url}" >> ${HOME}/.ssh/authorized_keys
