#! /bin/bash

. "${KMN_CONFIG}"

OPTSTRING=":u:r:k:"
while getopts ${OPTSTRING} opt; do
  case ${opt} in
    u)
      PUBKEY_USERNAME="${OPTARG}"
      ;;
    r)
      PUBKEY_REPO="${OPTARG}"
      ;;
    k)
      KEY_NAME="${OPTARG}"
      ;;
    ?)
      echo "Invalid option: -${OPTARG}."
      exit 1
      ;;
  esac
done

gh_baseurl="https://raw.githubusercontent.com/${PUBKEY_USERNAME}/${PUBKEY_REPO}/master"
gh_key_url="${gh_baseurl}/${KEY_NAME}.pub"

echo "${gh_key_url}"
curl "${gh_key_url}" >> "${HOME}/.ssh/authorized_keys"
