#! /bin/bash

. "${KMN_CONFIG}"

OPTSTRING=":t:k:"
while getopts ${OPTSTRING} opt; do
  case ${opt} in
    t)
      KEY_TYPE="${OPTARG}"
      ;;
    k)
      KEY_NAME="${OPTARG}"
      ;;
    ?)
      echo "Invalid option: -${OPTARG}."
      exit 1
      ;;
  esac
done

key_priv_path="${HOME}/.ssh/${KEY_NAME}"
key_id_path="${HOME}/.ssh/id_${KEY_TYPE}"

# automatically creates dir, if non-existing
ssh-keygen -q -t "${KEY_TYPE}" -C "${KEY_NAME}" -f "${key_priv_path}"

# TODO: add argument to make a key default
ln -sf "${key_priv_path}" "${key_id_path}"
ln -sf "${key_priv_path}.pub" "${key_id_path}.pub"
