#! /bin/bash

repo_local_path="${HOME}/pit/${GSH_GH_REPO_NAME}"
repo_remote_path="ssh://git@github.com/${GSH_GH_USERNAME}/${GSH_GH_REPO_NAME}.git"

git clone "${repo_remote_path}" "${repo_local_path}"