#! /bin/bash

# sudo apt -y update &&
#     sudo apt -y install ssh gh git

# github.com/login/device
# --git-protocol does not change how you login, it changes how subsequent git operations are handled
# after signig with --web option, it still automatically creates and downloads the token
echo "Open URL: github.com/login/device"
gh auth status ||
    gh auth login --hostname github.com \
    --git-protocol https \
    --web \
    --scopes "${GSH_GH_SCOPES}"

gh config set --host github.com prompt disabled