#! /bin/bash

repo_local_path="${HOME}/pit/${GSH_GH_REPO_NAME}"
key_pub_path="${HOME}/.ssh/${GSH_KEY_NAME}.pub"

cp "${key_pub_path}" "${repo_local_path}"

(cd "${repo_local_path}" &&
    git add --all . &&
    git commit -m "${GSH_KEY_NAME}" &&
    git push)