#! /bin/bash

OPTSTRING=":u:r:k:"
while getopts ${OPTSTRING} opt; do
  case ${opt} in
    u)
      KMN_PUBKEY_USER="${OPTARG}"
      ;;
    r)
      KMN_PUBKEY_REPO="${OPTARG}"
      ;;
    k)
      KMN_KEY_NAME="${OPTARG}"
      ;;
    ?)
      echo "Invalid option: -${OPTARG}."
      exit 1
      ;;
  esac
done

gh_baseurl="https://raw.githubusercontent.com/${KMN_PUBKEY_USER}/${KMN_PUBKEY_REPO}/master"
gh_key_url="${gh_baseurl}/${KMN_KEY_NAME}.pub"

curl "${gh_key_url}" >> ${HOME}/.ssh/authorized_keys
