#! /bin/bash

OPTSTRING=":k:"
while getopts ${OPTSTRING} opt; do
  case ${opt} in
    k)
      KMN_KEY_NAME="${OPTARG}"
      ;;
    ?)
      echo "Invalid option: -${OPTARG}."
      exit 1
      ;;
  esac
done

key_pub_path="${HOME}/.ssh/${KMN_KEY_NAME}.pub"

gh ssh-key add "${key_pub_path}" --type authentication
gh config set --host github.com git_protocol ssh
    